# -*- coding: utf-8 -*-
"""QuizHamoyeA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15h1rAXMiN7G0rDnBuVGHcatHrBAOyZbo
"""

#Question 6
import pandas as pd
df=pd.read_csv('fuel1.csv',encoding='ISO-8859-1')

df.isnull().sum()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
gas = grouped.get_group("gas")
gas.mean()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
oil = grouped.get_group("oil")
oil.mean()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
waste = grouped.get_group("waste")
waste.mean()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
nuclear = grouped.get_group("nuclear")
nuclear.mean()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
coal = grouped.get_group("coal")
coal.mean()

#QUESTION 3
grouped = df.groupby(df.fuel_type_code_pudl)
other = grouped.get_group("other")
other.mean()

#Question 4
df.describe(include='all')

#Question 9 and 10
grouped = df.groupby(df.report_year)
y1 = grouped.get_group(1997)
y1.mean()

#Question 8
import seaborn as sns
import matplotlib.pyplot as plt
corrMatrix = df.corr()
sns.heatmap(corrMatrix, annot=True)
plt.show()

#Question 5
df['fuel_qty_burned'].skew()

#Question 5
df['fuel_qty_burned'].kurtosis()

